### ISSUE TITLE
Bluetooth Emulator

### ISSUE THREAD

**Issue by mohamad-abuzaid** [cheng81/Android-Bluetooth-Simulator#5]
Hello cheng,
         I installed the emulator.apk on 2 emulators and after running the btsim server. I get this error when I click "Start Server" on one of the emulators:

Server started on port 8199
press any key to exit
accepting a new connection from /127.0.0.1
new string is : '3'
new string is : '3]'
creating command MODIFYSERVICE
read parameter: type=added
read parameter: tcp.port=8125
read parameter: service.uuid=419bbc68-c365-4c5e-8793-5ebff85b908c
read parameter: bt.address=93:52:16:DF:AA:CB
java.lang.NullPointerException
    at dk.itu.btemu.cmd.ModifyService.work(ModifyService.java:28)
    at dk.itu.btemu.cmd.BaseCommand.run(BaseCommand.java:47)
    at java.lang.Thread.run(Thread.java:679)

Any help!!!

**Comment by cheng81** [comment]
Hi, you probably have to first "enable" the fake bluetooth. Of course, this is a bug in the emulator application (I don't check if the bluetooth module is turned on or not).
